### ISSUE TITLE
grunt autoshot throwing depreciation errors then fails

### ISSUE THREAD

**Issue by fi5u** [siygle/grunt-autoshot#6]
Hi,

I'm using _autoshot_ in my Gruntfile. The task currently looks like:

```
autoshot: {
    default_options: {
        options: {
            path: 'dev',
            remote: {
                files: [
                    { src: "http://www.google.com", dest: "google.png" }
                ]
            },
            viewport: [
                '1920x1080',
                '1024x768',
                '640x960'
            ]
        },
    },
}
```

When I run `grunt autoshot` I get the following error:

```
Running "autoshot:default_options" (autoshot) task
phantom stderr: 2013-10-29 15:38:04.017 phantomjs[9080:507] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 

phantom stderr: 2013-10-29 15:38:04.016 phantomjs[9079:507] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 


/Users/tommy/Sites/generator-site-playground/node_modules/grunt-contrib-compass/node_modules/tmp/lib/tmp.js:261
  throw err;
        ^
TypeError: Cannot call method 'createPage' of undefined
    at /Users/tommy/Sites/generator-site-playground/node_modules/grunt-autoshot/tasks/autoshot.js:49:12
    at /Users/tommy/Sites/generator-site-playground/node_modules/grunt-autoshot/node_modules/node-phantom-simple/node-phantom-simple.js:161:20
    at /Users/tommy/Sites/generator-site-playground/node_modules/grunt-autoshot/node_modules/node-phantom-simple/node-phantom-simple.js:133:32
    at ChildProcess.exithandler (child_process.js:641:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Socket.<anonymous> (child_process.js:948:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
```

How can I correct this? Have I configured the task wrongly?
Many thanks

**Comment by adamcbrewer** [comment]
This is related to #7 - try download phantomJS v1.9.0.
